# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Sergio Corato
org_slug: sergiocorato
rebel_module_groups:
- mrp_bom_evaluation
- mrp_bom_evaluation_simple
- mrp_production_bom_create,mrp_production_calendar,mrp_production_change_product_fix,mrp_production_component_delete
- mrp_production_active_move_line_fix,mrp_employee_productivity,mrp_bom_sale_pricelist,mrp_bom_operation_estimate
- mrp_bom_attachment_export,mrp_bom_line_all_attachments,mrp_bom_line_group
repo_description: Tools for Italian companies
repo_name: Extra Efatto tools
repo_slug: e-efatto
repo_website: https://github.com/sergiocorato/e-efatto
travis_apt_packages: []
travis_apt_sources: []

