name: tests

on:
  pull_request:
    branches:
      - "12.0*"
  push:
    branches:
      - "12.0"
      - "12.0-ocabot-*"

jobs:
  unreleased-deps:
    runs-on: ubuntu-latest
    name: Detect unreleased dependencies
    steps:
      - uses: actions/checkout@v3
      - run: |
          for reqfile in requirements.txt test-requirements.txt ; do
              if [ -f ${reqfile} ] ; then
                  result=0
                  # reject non-comment lines that contain a / (i.e. URLs, relative paths)
                  grep "^[^#].*/" ${reqfile} || result=$?
                  if [ $result -eq 0 ] ; then
                      echo "Unreleased dependencies found in ${reqfile}."
                      exit 1
                  fi
              fi
          done
  test:
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/oca/oca-ci/py3.6-ocb12.0:latest
            include: "mrp_bom_evaluation"
            name: test with OCB
            makepot: "false"
          - container: ghcr.io/oca/oca-ci/py3.6-ocb12.0:latest
            include: "mrp_bom_evaluation_simple"
            name: test with OCB
            makepot: "false"
          - container: ghcr.io/oca/oca-ci/py3.6-ocb12.0:latest
            include: "mrp_production_demo,mrp_manual_procurement_subcontractor"
            name: test with OCB
            makepot: "false"
          - container: ghcr.io/oca/oca-ci/py3.6-ocb12.0:latest
            exclude: "mrp_bom_evaluation,mrp_bom_evaluation_simple,mrp_production_demo,mrp_manual_procurement_subcontractor"
            name: test with OCB
            makepot: "false"
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      INCLUDE: "${{ matrix.include }}"
      EXCLUDE: "${{ matrix.exclude }}"
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install pip dep
        run: pip3 install pika
      - name: Install pip iot
        run: pip3 install odoo12-addon-iot
      - name: Install mrp_sale_info_link module from other repo
        run: pip3 install -e "git+https://github.com/sergiocorato/efatto@12.0#egg=odoo12-addon-mrp_sale_info_link&subdirectory=setup/mrp_sale_info_link"
      - name: Install sale_order_analytic_all module from other repo
        run: pip3 install -e "git+https://github.com/sergiocorato/e-account@12.0#egg=odoo12-addon-sale_order_analytic_all&subdirectory=setup/sale_order_analytic_all"
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Check licenses
        run: manifestoo -d . check-licenses
      - name: Check development status
        run: manifestoo -d . check-dev-status --default-dev-status=Beta
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
